version: '3.8'

services:
  app:
    build:
      context: .
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY} # Pass the env var from Coolify's environment as a build arg
    ports:
      - "8080" # Expose container port 8080 to a dynamic host port. Coolify's reverse proxy will pick this up.
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY} # This will be injected by Coolify
      - PORT=8080 # Ensure the server inside the container uses this port
    restart: unless-stopped
    # If you need to mount volumes, for example, for logs or other persistent data,
    # you can define them here. For a static frontend, this is often not necessary.
    # volumes:
    #   - ./logs:/usr/src/app/logs # Example volume mount
networks:
  default:
    driver: bridge
